name: "Build & Publish"
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  beanstalkd:
    name: Beanstalkd
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: beanstalkd/beanstalkd
      
      - name: Replace with local Dockerfile
        run: curl https://raw.githubusercontent.com/ssi-anik/docker-builds-beanstalkd/master/Dockerfile --output Dockerfile
                
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DH_USERNAME }}
          password: ${{ secrets.DH_TOKEN }}

      - name: Build and publish
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DH_USERNAME }}/beanstalkd:latest
